### PR TITLE
added new weapons to goodguy selection

### PR DESCRIPTION
**Pull request by BenCopeland**
Had a vapid moment and forgot to add new weapons to a little portion.

### CODE REVIEW

**Comment by madduxTim** [comment]
:+1:

**Comment by sylviama** [comment]
Ops, my merge caused a conflicts on your pr. I thought I added exactly same thing as yours... maybe it's the order difference...? Not sure. Anyway, this part is already taken care of. Don't worry about it...

**Comment by BenCopeland** [comment]
Well I got rid of war axe, changed it to battle axe to match common rpg naming conventions. But we still need to merge this branch in for those changes to match up and to also have the damage range feature.

**Comment by sylviama** [comment]
sure. merge it then. :+1:

**Pull request merged**
