### PR TITLE
If no value selected, cannot move forward function

### PR DESCRIPTION
**Pull request by sylviama**

### CODE REVIEW

**Comment by sylviama** [comment]
besides the "no selection cannot move" function, I also fixed the bug that if you click "back", the hover-overed message will double(append twice).

**Comment by sylviama** [comment]
screen shot 2016-04-26 at 11 07 10 pm

**Comment by sylviama** [comment]
on my screen, some of them shows like the pic above. I kind of fix it by using a cheating way (which means I don't think that's the root cause)- change the append order of the two message (switch healthBonus and strengthBonus)... feel free to modify it if you find the root cause...

**Comment by madduxTim** [comment]
I'll see if I can find a solution to this Sylvia. I only have a couple
hours to put in on this though.

**Comment by sylviama** [comment]
Totally understandable. At least now it looks clean enough. Good enough for tonight's presentation.

**Comment by madduxTim** [comment]
:+1:

**Comment by BenCopeland** [comment]
👍

**Pull request merged**
