### PR TITLE
added new weapons, range of damage coming next

### PR DESCRIPTION
**Pull request by BenCopeland**
This is a pr for just the added weapons, and new weapons added to the hover stuff. I am gonna do the weapon range stuff tmrw.

### CODE REVIEW

**Comment by BenCopeland** [comment]
time out, Ill condense a few functions and then make another commit. TBA sometime tmrw probably.

**Comment by sylviama** [comment]
Tim updated the hover over part into another type of code, could you change the hover over part with it as well? If you don't have time, I will modify it tomorrow. Thanks

**Comment by BenCopeland** [comment]
Yes, I can pull his changes down after it merges and update this PR.

**Comment by BenCopeland** [comment]
I would like to merge this with the current updates. Its just the added weapons, I still havent tried condensing the hover stuff, and I still want to add the range of damage, but I already made a different branch for that feature. Just wanted to make sure everyone had the updated weapons.

**Comment by sylviama** [comment]
👍

**Pull request merged**
